import time
import pytest

from HRM_Login.Login import Login


@pytest.mark.usefixtures("setup")
class Test_Login:
    def test_login(self,setup):
        object = Login(self.driver)
        object.login("Admin", "admin123")
        object.login1()
        time.sleep(5)
        object.login2("heyy")
        time.sleep(7)
        object.login3(87)
        # object.login4()
        time.sleep(6)
        object.login5()
        object.login6()
        time.sleep(7)
        object.login7()
        object.login8("cbe")
        time.sleep(3)
        object.login9("a")
        object.login10()
        time.sleep(3)
        object.login11()
        object.login12("a")
        time.sleep(5)
        object.login13()
        # object.login14()
        # object.login15()
        # time.sleep(6)
        # object.login16("pic")
        # object.login17()
        # time.sleep(4)
        # object.login18()
        # object.login19()
        # time.sleep(5)
        # object.login20("Heyy")
        # object.login21("c")
        # time.sleep(4)
        # object.login22("a")
        # object.login23()
        # time.sleep(3)
        # object.login24()
        # object.login25()
        # object.login26()
        # time.sleep(5)
        # object.login27("pic")
        # object.login28("lovemyself")
        # time.sleep(4)
        # object.login29()
        # object.key1()
        # object.key2("CTS")
        # object.key3("DataAnalyst")
        # object.key4()
        # object.key5()
        # object.key6("Crescent")
        # object.key7("computerscience")
        # object.key8(2024)
        # object.key9(9.2)
        # object.key10()
        # object.key11()
        # object.key12(12)
        # object.key13()
        # object.key14()
        # object.key15()
        # object.key16()
        object.logout()
        time.sleep(5)
